# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('male', 'female')], max_length=20)),
                ('RelationshipStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('live_in_relationship', 'live_in_relationship'), ('fling', 'fling')], max_length=20)),
                ('Occupation', models.CharField(choices=[('Student', 'Student'), ('Profession', 'Profession'), ('Employment', 'Employment'), ('Business', 'Business')], max_length=20)),
                ('Student', models.CharField(choices=[('School', 'School'), ('College', 'College')], max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Email_id', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Story', models.CharField(max_length=20)),
            ],
        ),
    ]
