# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170610_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaldetails',
            fields=[
                ('Pid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('male', 'female')], max_length=20)),
                ('RelationshipStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('live_in_relationship', 'live_in_relationship'), ('fling', 'fling')], max_length=20)),
                ('Occupation', models.CharField(choices=[('Student', 'Student'), ('Profession', 'Profession'), ('Employment', 'Employment'), ('Business', 'Business')], max_length=20)),
                ('Student', models.CharField(choices=[('School', 'School'), ('College', 'College')], max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Age', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
