# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170611_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='Email_id',
            field=models.EmailField(blank=True, max_length=20),
        ),
    ]
