# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_personaldetails_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.Personaldetails')),
                ('q1', models.IntegerField(blank=True, choices=[(0, 'option1'), (1, 'option2'), (2, 'option3'), (3, 'option4')], null=True)),
                ('q2', models.IntegerField(blank=True, choices=[(0, 'option1'), (1, 'option2'), (2, 'option3'), (3, 'option4')], null=True)),
                ('q3', models.IntegerField(blank=True, choices=[(0, 'option1'), (1, 'option2'), (2, 'option3'), (3, 'option4')], null=True)),
                ('q4', models.IntegerField(blank=True, choices=[(0, 'option1'), (1, 'option2'), (2, 'option3'), (3, 'option4')], null=True)),
                ('q5', models.IntegerField(blank=True, choices=[(0, 'option1'), (1, 'option2'), (2, 'option3'), (3, 'option4')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('Rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.Personaldetails')),
                ('result', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Email_id',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Pid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Student',
            field=models.CharField(blank=True, choices=[('School', 'School'), ('College', 'College')], max_length=20, null=True),
        ),
    ]
