# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20170619_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='q1',
            field=models.IntegerField(blank=True, choices=[('option1', 0), ('option2', 1), ('option3', 2), ('option4', 3)], null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='q2',
            field=models.IntegerField(blank=True, choices=[('option1', 0), ('option2', 1), ('option3', 2), ('option4', 3)], null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='q3',
            field=models.IntegerField(blank=True, choices=[('option1', 0), ('option2', 1), ('option3', 2), ('option4', 3)], null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='q4',
            field=models.IntegerField(blank=True, choices=[('option1', 0), ('option2', 1), ('option3', 2), ('option4', 3)], null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='q5',
            field=models.IntegerField(blank=True, choices=[('option1', 0), ('option2', 1), ('option3', 2), ('option4', 3)], null=True),
        ),
    ]
