# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20170619_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=portal.models.Personaldetails),
        ),
    ]
