# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20170620_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='q1',
            field=models.IntegerField(blank=True, choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='q2',
            field=models.IntegerField(blank=True, choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='q3',
            field=models.IntegerField(blank=True, choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='q4',
            field=models.IntegerField(blank=True, choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='q5',
            field=models.IntegerField(blank=True, choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], null=True),
        ),
    ]
