# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20170620_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
