# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20170620_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Student',
            field=models.CharField(choices=[('School', 'School'), ('College', 'College')], max_length=20),
        ),
        migrations.AlterField(
            model_name='responses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=portal.models.Personaldetails),
        ),
    ]
