# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20170620_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.IntegerField(),
        ),
    ]
