# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20170620_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.Personaldetails'),
        ),
    ]
