# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20170623_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('Storyid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Location', models.CharField(max_length=30)),
                ('Story', models.TextField()),
                ('Time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
