# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20170626_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stories',
            new_name='Story',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story',
            new_name='story_text',
        ),
    ]
