# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20170704_1152'),
        ('portal', '0024_auto_20170704_1720'),
    ]

    operations = [
    ]
