# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_merge_20170705_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='id',
        ),
        migrations.AddField(
            model_name='responses',
            name='person',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.Personaldetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='Rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.Personaldetails'),
        ),
    ]
