# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20170705_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.Personaldetails'),
        ),
        migrations.AlterField(
            model_name='result',
            name='Rid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.Personaldetails'),
        ),
    ]
