# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_responses_result'),
    ]

   # operations = [
        #migrations.AddField(
          #  model_name='personaldetails',
          #  name='Resultp',
         #   field=models.CharField(blank=True, max_length=50, null=True),
        #),
        #migrations.AddField(
       #     model_name='personaldetails',
      #      name='Score',
     #       field=models.IntegerField(blank=True, null=True),
    #    ),
   # ]
