# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20170706_2314'),
    ]

    operations = [
      #  migrations.AddField(
      #      model_name='personaldetails',
      #      name='Date',
      #      field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 9, 18, 39, 39, 503103, tzinfo=utc)),
     #       preserve_default=False,
      # ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Age',
            field=models.IntegerField(verbose_name='Your Age'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='City',
            field=models.CharField(max_length=20, verbose_name='Which City you live in ?'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Email_id',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email Id '),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('male', 'female'), ('Other', 'Other')], max_length=20, verbose_name='Select Your Gender'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Name',
            field=models.CharField(max_length=20, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Occupation',
            field=models.CharField(choices=[('Professional', 'Professional'), ('Business', 'Business'), ('NA', 'Not Applicable')], max_length=20, verbose_name='Your Work'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='RelationshipStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('live_in_relationship', 'live_in_relationship'), ('fling', 'fling')], max_length=20, verbose_name='Your Current Relationship Status'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Student',
            field=models.CharField(choices=[('School', 'School'), ('College', 'College'), ('NA', 'Not Applicable')], max_length=20, verbose_name='Student'),
        ),
    ]
