# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_auto_20170710_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_text',
            field=models.TextField(default='Notext\x1b[D\x1b[D'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='story_title',
            field=models.CharField(default='No Text', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='portal.Story'),
        ),
    ]
