# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_auto_20170710_1311'),
        ('portal', '0030_auto_20170710_0009'),
    ]

    operations = [
    ]
