# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_merge_20170713_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='comments',
        ),
        migrations.AlterField(
            model_name='responses',
            name='q2',
            field=models.IntegerField(choices=[(0, 'I am not particularly discouraged about the future.'), (1, 'I feel discouraged about the future'), (2, 'I feel I have nothing to look forward to.'), (3, 'I feel the future is hopeless and that things cannot improve.')]),
        ),
    ]
