# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_auto_20170713_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='City',
            field=models.CharField(max_length=20, verbose_name='Enter the name of your city'),
        ),
    ]
