# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_auto_20170713_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='sentiment',
            field=models.IntegerField(default=0),
        ),
    ]
