# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_auto_20170713_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='Resultp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='Score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('Other', 'Other')], max_length=20, verbose_name='Select Your Gender'),
        ),
    ]
